theme: jekyll-theme-minimal
title: About me: 
description: Devops Engineer with 2.5 yrs of experience in deployments over large infrastructure. Proficient with configuration management tools, and in developing CI/CD pipelines.
